### ISSUE TITLE
Can't build sdk, duplicate patch file error

### ISSUE THREAD

**Issue by MaciekBaron** [MiyooCFW/buildroot#1]
On a fresh Ubuntu installation (VB) I run:
    
    sudo apt install git gcc build-essential libsdl2-dev libopenmpt-modplug-dev libsdl2-mixer-dev libminizip-dev bison make python
    git clone https://github.com/MiyooCFW/buildroot.git
    cd buildroot
    make sdk

After a considerable amount of time I get:

    Applying 0001-avoid-kernel-if_ether.h.patch using patch: 
    Error: duplicate filename '0001-avoid-kernel-if_ether.h.patch'
    Conflicting files are:
      already applied: /home/maciek/buildroot/package/musl/0001-avoid-kernel-if_ether.h.patch
      to be applied  : /home/maciek/buildroot/package/musl/0001-avoid-kernel-if_ether.h.patch
    make[1]: *** [package/pkg-generic.mk:206: /home/maciek/buildroot/output/build/musl-1.1.24/.stamp_patched] Error 1
    make: *** [Makefile:84: _all] Error 2

Did I miss a step?

**Comment by MaciekBaron** [comment]
Just an update, after removing the patch files from `buildroot/package/musl/` it seems to have built correctly, but I still need to test. Perhaps you should consider removing them?

**Comment by TriForceX** [comment]
We are getting many reports about build problems, so we are checking everything again, thanks for reporting.

**Comment by TriForceX** [comment]
It should work now, and yea, it was a wrong merge so these files (and others) didnt got deleted.
