### ISSUE TITLE
Problems with sources.buildroot.net addresses

### ISSUE THREAD

**Issue by jeffbzrr** [MiyooCFW/buildroot#142]
Hello, I'm trying to compile and but I'm getting the error:
make: *** [package/pkg-generic.mk:189: /home/jeff/miyoo-buildroot/buildroot/output/build/host-ccache-3.7.12/.stamp_downloaded] Error 1

I noticed that before that it tries to download ccache from the following address:
http://sources.buildroot.net/ccache-3.7.12.tar.xz

This address no longer exists, however, the address 
http://sources.buildroot.net/ccache/ccache-3.7.12.tar.xz 
exists and is even used in another part of the process.

I'm asking for help because I can't find where this is being done. The address is assembled using variables "main url" + "package name" + "version", and this makes it so that I can't find in the code where this is done. 

I also tried using a current version of buildroot and getting some config files from here, but the current buildroot complains that there are legacy configurations. That's another way I'm trying, but it seems to me easier to solve this ccache problem. 

Thank you.

**Comment by jeffbzrr** [comment]
I downloaded the current version of buildroot and tweaked that it complains about being legacy. I compiled everything but didn't create an.img file, maybe I missed setting something up. Unfortunately, I've been hyperfocused on this build since last night, but I have to stop now. I also couldn't solve the download problem =/

**Comment by tiopex** [comment]
Check the build logs of Buildroot from our CI https://github.com/MiyooCFW/buildroot/actions and compare the logs. There should be no issue with downloading the ccache package.

**Comment by jeffbzrr** [comment]
Yes, I see. The ccache downloads normally and for some reason here the generated link is broken. Something in my system is broken. Thank you.

**Comment by jeffbzrr** [comment]
I found out what the problem was. Fedora changed wget to wget2 but kept calling it wget. I installed an old version and the problem disappeared. 

(I'm having other problems right now, I'll probably try it on another distribution.)

**Comment by Apaczer** [comment]
tks for info, other repos are having same headache with newer wget. Small step-by-step for others to ref. https://github.com/ZoranStojsavljevic/Fedora.40_wget2_solution . 
Generally it is advised to use Debian for BR2
