### ISSUE TITLE
[BTRFS] Regression on Video recording performance with `ffmpeg`

### ISSUE THREAD

**Issue by Apaczer** [MiyooCFW/buildroot#67]
Low system responsinvness, seen even in GMenu2X after launching VIDEO record. It wasn't perfect previously but was at least functional.

**Comment by Apaczer** [comment]
Looks like BTRFS limitation, even vfat in sync mode is way faster.

**Comment by tiopex** [comment]
I think it's more CPU-intensive, than vfat
